export const sagaActions = {
      FETCH_COURSES_SAGA_ACTION: "FETCH_COURSES_SAGA_ACTION",
      FETCH_COURSE_BY_ID: "FETCH_COURSE_BY_ID",
      AUTHENTICATE_USER: "AUTHENTICATE_USER",
      ADD_NEW_USER: "ADD_NEW_USER",
      GET_USER: "GET_USER"
  };